version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: always
    container_name: aeva_postgres
    environment:
      POSTGRES_DB: aeva_db
      POSTGRES_USER: aeva_user
      POSTGRES_PASSWORD: aeva_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aeva_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aeva_user -d aeva_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ChromaDB for vector storage
  chromadb:
    image: chromadb/chroma:latest
    restart: always
    container_name: aeva_chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - aeva_network
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]

volumes:
  postgres_data:
    driver: local
  chroma_data:
    driver: local

networks:
  aeva_network:
    driver: bridge 