import { useEffect, useRef, useState } from "react";
import { motion } from "framer-motion";
import { Bot, User } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { AgentWorkboard } from "@/components/chat/AgentWorkboard";
import { QuizCard } from "@/components/chat/QuizCard";
import { FlashcardCard } from "@/components/chat/FlashcardCard";
import { NoteCard } from "@/components/chat/NoteCard";
import { ExamPrepOfferCard } from "@/components/chat/ExamPrepOfferCard";
import { ChatErrorCard } from "@/components/chat/ChatErrorCard";
import { DebugInfoPanel } from "@/components/chat/DebugInfoPanel";
import { useAuth } from "@/contexts/AuthContext";
import { useMedia } from "@/hooks/api";
import { useFeature } from "@/hooks/useFeature";
import type { GeneratedImage } from "@/types";
import { MarkdownContent } from "@/components/chat/MarkdownContent";
import { SourceCards } from "@/components/chat/SourceCards";
import {
  SuggestedActions,
  type FeedbackRating,
} from "@/components/chat/SuggestedActions";
import { ThinkingIndicator } from "@/components/chat/ThinkingIndicator";
import { cn } from "@/lib/utils";
import { copyRich, markdownToPlainText } from "@/lib/clipboard";
import type { ThinkingHint } from "@/lib/loadingMessages";
import { isTeamTurn } from "@/lib/messageMeta";
import type {
  AgentInfo,
  Message,
  QuizContent,
  QuizOptions,
  ToolUsed,
} from "@/types";

// Only tools worth surfacing get a source badge. `general` is a plain
// conversational answer (no badge), and anything unlisted is skipped too.
const TOOL_LABEL: Partial<Record<ToolUsed, string>> = {
  web_search: "Web",
  media_llm: "Notes",
  quiz_generator: "Quiz",
  image_generator: "Image",
  product_info: "App Guide",
};

// The "⚡ powered by: <model>" trailer the backend appends for Developer Mode
// users is baked into persisted message text. If the flag is later turned
// off (or a message predates the per-user gate), strip it at render time so
// non-debug users never see it.
const POWERED_BY_RE = /\n+---\n_⚡ powered by:[^_\n]*_\s*$/;

// The optimistic assistant bubble carries this prefix until the final stream
// frame brings the persisted id. Such an id must never be saved anywhere.
const PLACEHOLDER_PREFIX = "stream-";
// Below this many characters an answer is a greeting, an acknowledgement or
// Aeva describing itself: nothing worth a quiz or flashcards.
const GENERATOR_MIN_CHARS = 300;
// Response categories that carry no study content either.
const NON_CONTENT_TYPES = new Set(["CLARIFICATION", "NOT_RELEVANT", "ERROR"]);

/** Hide "Create Quiz / Flashcards" on meta or very short answers. */
function isMetaAnswer(msg: Message): boolean {
  if (msg.meta?.tool_used === "product_info") return true;
  if (msg.meta?.response_type && NON_CONTENT_TYPES.has(msg.meta.response_type)) {
    return true;
  }
  return msg.content.trim().length < GENERATOR_MIN_CHARS;
}

/**
 * Images Aeva generated for an answer. Each is a media-library row; the
 * signed URL captured at generation time expires, so prefer the fresh one
 * from the (cached) media list and fall back to the stored URL. Mounted only
 * when a message actually carries images.
 */
function GeneratedImages({ images }: { images: GeneratedImage[] }) {
  const { data: media } = useMedia();
  const freshUrl = (img: GeneratedImage) =>
    media?.find((m) => m.id === img.media_id)?.signed_url || img.url;

  return (
    <div className="mt-3 flex flex-wrap gap-2">
      {images.map((img) => {
        const url = freshUrl(img);
        if (!url) return null;
        return (
          <a
            key={img.media_id}
            href={url}
            target="_blank"
            rel="noopener noreferrer"
            title={img.file_name || "Generated image"}
            className="block max-w-sm overflow-hidden rounded-xl border border-border/60 transition-shadow hover:shadow-glow"
          >
            <img
              src={url}
              alt={img.alt || img.file_name || "Image generated by Aeva"}
              loading="lazy"
              className="max-h-80 w-full object-contain"
            />
            {img.style_label && (
              <span className="flex items-center gap-1.5 border-t border-border/50 bg-muted/40 px-2.5 py-1 text-[11px] text-muted-foreground">
                <span className="rounded-full bg-brand-1/10 px-1.5 py-0.5 font-medium text-brand-1">
                  {img.style_label}
                </span>
                {img.alt && <span className="truncate">{img.alt}</span>}
              </span>
            )}
          </a>
        );
      })}
    </div>
  );
}

export function ChatMessages({
  messages,
  mediaAvailable,
  quizBusy,
  thinkingHint,
  onAction,
  onFollowup,
  onGenerateQuiz,
  onCreateFlashcards,
  onOpenQuiz,
  onOpenFlashcards,
  onSaveNote,
  onRetry,
  onRetryAgent,
  onFeedback,
  onRegenerate,
  highlightId,
  followOnLoad = true,
  noteActions = false,
}: {
  messages: Message[];
  mediaAvailable: boolean;
  quizBusy: boolean;
  thinkingHint?: ThinkingHint;
  onAction: (message: string, sourceContent: string) => void;
  onFollowup: (prompt: string, title: string) => void;
  onGenerateQuiz: (
    topic: string,
    options: QuizOptions,
    sourceContent?: string,
  ) => void;
  onCreateFlashcards: (sourceContent: string) => void;
  onOpenQuiz: (quiz: QuizContent) => void;
  onOpenFlashcards: (setId: string) => void;
  /** Save an answer as an editable note; resolves true on success. */
  onSaveNote: (
    messageId: string,
    content: string,
    topic: string,
  ) => Promise<boolean>;
  /** Re-send a failed turn (by its message id) from its error card. */
  onRetry: (messageId: string) => void;
  /** Re-run one failed agent of a multi-agent turn. */
  onRetryAgent: (messageId: string, agent: AgentInfo) => void;
  /** Thumbs up / down on an answer (`null` clears); resolves true on success.
   *  Omit to hide the controls. */
  onFeedback?: (
    messageId: string,
    rating: FeedbackRating | null,
    toolUsed?: string,
  ) => Promise<boolean>;
  /** "Regenerate" on the latest answer: re-send its question. Omit to hide. */
  onRegenerate?: (messageId: string) => void;
  /** Message to scroll to and flash-highlight (e.g. opened from a bookmark). */
  highlightId?: string | null;
  /** Scroll to the newest message when the conversation first loads or
   *  switches (default). Pass false where the thread sits below other
   *  content the user came for (the exam topic page): loading history then
   *  leaves the viewport alone, while sends and streaming still follow. */
  followOnLoad?: boolean;
  /** Offer "Save as revision sheet" / "Important questions" on answers.
   *  Only the main chat turns these into saved notes, so it opts in. */
  noteActions?: boolean;
}) {
  // Developer Mode: the single switch for every debug-only element here (tool
  // badge, diagnostics panel). Normal users get a production-clean bubble.
  const { isDebugUser } = useAuth();
  const notesEnabled = useFeature("notes");
  const bottomRef = useRef<HTMLDivElement>(null);
  // Rendered markdown nodes, so Copy yields clean text + rich HTML.
  const contentRefs = useRef<Map<string, HTMLDivElement>>(new Map());
  // Message row containers, keyed by id, for scroll-to-message.
  const rowRefs = useRef<Map<string, HTMLDivElement>>(new Map());
  // The highlight we've already scrolled to, so it fires once per target.
  const appliedHighlight = useRef<string | null>(null);
  // Whether the viewport is currently pinned near its bottom. Refreshed on every
  // scroll so we can read the user's intent *before* new content pushes the
  // bottom down — streaming only follows when they were already at the bottom.
  // Defaults to true (and is reset to true on a conversation switch) so the very
  // first render still lands on the newest message.
  const nearBottomRef = useRef(true);
  // Identifies the loaded conversation; when it changes we've switched threads
  // (or loaded history), so re-arm the auto-scroll to land at the bottom.
  const convoKeyRef = useRef<string | null>(null);
  // Last user-message id, to tell a brand-new user turn (which always scrolls
  // into view) from an assistant streaming update (which respects scroll pos).
  const lastUserIdRef = useRef<string | null>(null);
  const [flashId, setFlashId] = useState<string | null>(null);
  // Thumbs ratings changed in this view, by message id (`null` = cleared).
  // The server keeps the record in `messages.metadata.feedback`; a message
  // not touched here shows its saved rating (`meta.feedback`), so thumbs
  // survive a reload.
  const [ratings, setRatings] = useState<
    Record<string, FeedbackRating | null>
  >({});

  // Stable React keys across an id swap. When the final stream frame arrives,
  // the optimistic `stream-…` id of the answer (and the user bubble's client
  // id) is replaced by the persisted one in the same list position. The row
  // keeps the key it mounted with, so the finished bubble does not re-mount
  // and replay its enter animation, and the scroll heuristics below do not
  // mistake the swap for a new turn or a conversation switch. Only a swap is
  // aliased: at most two ids change and one of them is a placeholder.
  const prevIdsRef = useRef<string[]>([]);
  const keyAliasRef = useRef(new Map<string, string>());
  {
    const prev = prevIdsRef.current;
    const current = messages.map((m) => m.id);
    if (prev.length === current.length) {
      const changed = current
        .map((_, i) => i)
        .filter((i) => prev[i] !== current[i]);
      const isSwap =
        changed.length > 0 &&
        changed.length <= 2 &&
        changed.some((i) => prev[i].startsWith(PLACEHOLDER_PREFIX)) &&
        changed.every((i) => !current.includes(prev[i]));
      if (isSwap) {
        for (const i of changed) {
          keyAliasRef.current.set(
            current[i],
            keyAliasRef.current.get(prev[i]) ?? prev[i],
          );
        }
      }
    }
    prevIdsRef.current = current;
  }
  const keyOf = (m: Message) => keyAliasRef.current.get(m.id) ?? m.id;

  // Track whether the user is near the bottom of the scroll container. A user
  // scroll up disables auto-follow; scrolling back to the bottom re-enables it.
  useEffect(() => {
    let el: HTMLElement | null = bottomRef.current?.parentElement ?? null;
    while (el) {
      const oy = getComputedStyle(el).overflowY;
      if (oy === "auto" || oy === "scroll") break;
      el = el.parentElement;
    }
    if (!el) return undefined;
    const NEAR_BOTTOM_PX = 120;
    const onScroll = () => {
      const gap = el.scrollHeight - el.scrollTop - el.clientHeight;
      nearBottomRef.current = gap < NEAR_BOTTOM_PX;
    };
    el.addEventListener("scroll", onScroll, { passive: true });
    return () => el.removeEventListener("scroll", onScroll);
  }, []);

  // Follow the newest content only when the user is already near the bottom, so
  // streaming never yanks the viewport down while they read earlier messages. A
  // conversation switch re-arms the follow so a freshly opened thread still
  // starts at its newest message. Suppressed while a highlight target is pending
  // so it doesn't fight the jump-to-message scroll (opened from a bookmark).
  useEffect(() => {
    const convoKey = messages[0] ? keyOf(messages[0]) : null;
    const convoChanged = convoKey !== convoKeyRef.current;
    if (convoChanged) {
      convoKeyRef.current = convoKey;
      nearBottomRef.current = true;
    }
    // A turn the user just sent always scrolls into view — even though it's
    // immediately followed by the assistant placeholder, so the newest *user*
    // message (not the last message) is the signal. Assistant streaming keeps
    // the same user id, so it instead respects the near-bottom gate.
    const lastUser = messages.reduce<string | null>(
      (id, m) => (m.role === "user" ? keyOf(m) : id),
      null,
    );
    const userSent = lastUser !== null && lastUser !== lastUserIdRef.current;
    lastUserIdRef.current = lastUser;

    if (highlightId && appliedHighlight.current !== highlightId) return;
    if (!userSent && !nearBottomRef.current) return;
    // A thread that loads below other content must not pull the page down;
    // its first send is scrolled by the page itself.
    if (!followOnLoad && convoChanged) return;
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
    // keyOf reads render-time refs; it is stable for a given `messages`.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [messages, highlightId, followOnLoad]);

  // Scroll to and briefly flash the highlighted message once it's rendered.
  // The scroll is deferred to the next frame so it runs *after* the mount's
  // bottom-scroll and reliably wins the race, regardless of effect order.
  useEffect(() => {
    if (!highlightId || appliedHighlight.current === highlightId) return;
    const el = rowRefs.current.get(highlightId);
    if (!el) return; // history not loaded yet — reruns when messages arrive.
    appliedHighlight.current = highlightId;
    setFlashId(highlightId);
    // Defer past the mount's bottom-scroll and initial markdown/code layout so
    // this is the final scroll and the target row is at its settled position.
    const scrollT = window.setTimeout(() => {
      el.scrollIntoView({ behavior: "smooth", block: "center" });
    }, 120);
    const flashT = window.setTimeout(() => setFlashId(null), 2400);
    return () => {
      window.clearTimeout(scrollT);
      window.clearTimeout(flashT);
    };
  }, [highlightId, messages]);

  const copyMessage = (id: string, fallback: string) => {
    const el = contentRefs.current.get(id);
    const text = el?.innerText?.trim() || markdownToPlainText(fallback);
    return copyRich({ html: el?.innerHTML, text });
  };

  // Follow-up / action chips belong only on the newest answer; older cards
  // keep just Bookmark + Copy so the conversation stays focused.
  const lastAssistantId = messages
    .filter((m) => m.role === "assistant")
    .at(-1)?.id;
  // At most one exam-soon offer is on screen: the newest answer carrying one.
  const lastOfferId = messages
    .filter((m) => m.role === "assistant" && m.meta?.exam_prep_offer)
    .at(-1)?.id;

  return (
    <div
      className="mx-auto flex w-full max-w-4xl flex-col gap-5 px-4 py-6"
      data-analytics-private
      data-analytics-section="chat_thread"
    >
      {messages.map((msg, i) => {
        const prevUser = [...messages.slice(0, i)]
          .reverse()
          .find((m) => m.role === "user");
        const topic = prevUser?.content ?? "";
        // A multi-agent turn shows its team instead of a single loader.
        const team = isTeamTurn(msg.meta) ? msg.meta!.agents! : null;
        const retryAgent = (agent: AgentInfo) => onRetryAgent(msg.id, agent);
        const toolBadges = (
          msg.meta?.tools_used?.length
            ? msg.meta.tools_used
            : msg.meta?.tool_used
              ? [msg.meta.tool_used]
              : []
        ).filter((tool) => TOOL_LABEL[tool]);
        const rowKey = keyOf(msg);
        // Until the persisted id arrives nothing may reference this answer.
        const canPersist = !msg.id.startsWith(PLACEHOLDER_PREFIX);
        return (
          <motion.div
            key={rowKey}
            ref={(el) => {
              if (el) rowRefs.current.set(msg.id, el);
              else rowRefs.current.delete(msg.id);
            }}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.25 }}
            className={cn(
              "flex scroll-mt-24 gap-2 sm:gap-3",
              msg.role === "user" && "flex-row-reverse",
            )}
          >
            {/* Avatar is hidden on phones so message content gets the full width;
               role is still clear from alignment + colour. */}
            <span
              className={cn(
                "hidden h-8 w-8 shrink-0 place-items-center rounded-full sm:grid",
                msg.role === "user"
                  ? "bg-primary text-primary-foreground"
                  : "bg-brand-gradient text-white",
              )}
            >
              {msg.role === "user" ? (
                <User className="h-4 w-4" />
              ) : (
                <Bot className="h-4 w-4" />
              )}
            </span>

            <div
              className={cn(
                "rounded-2xl px-4 py-3 text-sm leading-relaxed transition-shadow duration-700",
                msg.role === "user"
                  ? "max-w-[85%] rounded-br-sm bg-primary text-primary-foreground"
                  : "min-w-0 max-w-full flex-1 glass rounded-bl-sm",
                flashId === msg.id &&
                  "ring-2 ring-brand-1 ring-offset-2 ring-offset-background",
              )}
            >
              {isDebugUser && toolBadges.length > 0 && (
                <div className="mb-2 flex flex-wrap gap-1">
                  {toolBadges.map((tool) => (
                    <Badge
                      key={tool}
                      variant="secondary"
                      className="gap-1 text-[10px] font-medium"
                    >
                      {TOOL_LABEL[tool]}
                    </Badge>
                  ))}
                </div>
              )}

              {msg.role === "assistant" ? (
                msg.meta?.error ? (
                  <ChatErrorCard
                    error={msg.meta.error}
                    onRetry={() => onRetry(msg.id)}
                  />
                ) : msg.streaming && !msg.content ? (
                  team ? (
                    <AgentWorkboard agents={team} live onRetry={retryAgent} />
                  ) : (
                    <ThinkingIndicator hint={thinkingHint} />
                  )
                ) : (
                  <div
                    ref={(el) => {
                      if (el) contentRefs.current.set(msg.id, el);
                      else contentRefs.current.delete(msg.id);
                    }}
                    className="learning-content prose prose-sm max-w-none dark:prose-invert prose-p:my-2 prose-pre:my-2"
                  >
                    <MarkdownContent
                      content={
                        isDebugUser
                          ? msg.content
                          : msg.content.replace(POWERED_BY_RE, "")
                      }
                      sources={msg.meta?.sources}
                    />
                    {msg.streaming && (
                      <span className="ml-0.5 inline-block h-4 w-[2px] animate-pulse bg-primary align-middle" />
                    )}
                  </div>
                )
              ) : (
                msg.content
              )}

              {/* Developer Mode: the "powered by" trailer. It is display-only
                 (sent as its own stream frame, kept as `meta.model`), so it
                 sits outside the copied content node. Older answers that
                 still carry the trailer in their text are left as they are. */}
              {isDebugUser &&
                msg.role === "assistant" &&
                !msg.streaming &&
                !msg.meta?.error &&
                !!msg.meta?.model &&
                !POWERED_BY_RE.test(msg.content) && (
                  <p className="mt-3 border-t border-border/60 pt-2 text-xs italic text-muted-foreground [overflow-wrap:anywhere]">
                    ⚡ powered by: {msg.meta.model}
                  </p>
                )}

              {/* Once text exists the team sits under it: live while agents
                 are still finishing, then a collapsed summary (also what a
                 reloaded conversation shows). */}
              {team && msg.role === "assistant" && !!msg.content && (
                <AgentWorkboard
                  agents={team}
                  live={!!msg.streaming}
                  onRetry={retryAgent}
                />
              )}

              {msg.meta?.images && msg.meta.images.length > 0 && (
                <GeneratedImages images={msg.meta.images} />
              )}

              {msg.meta?.sources && msg.meta.sources.length > 0 && (
                <SourceCards sources={msg.meta.sources} />
              )}

              {msg.meta?.quiz?.questions?.length ? (
                <QuizCard
                  quiz={msg.meta.quiz}
                  onStart={() => onOpenQuiz(msg.meta!.quiz!)}
                />
              ) : null}

              {msg.meta?.flashcards?.cards?.length ? (
                <FlashcardCard
                  flashcards={msg.meta.flashcards}
                  onStudy={() =>
                    onOpenFlashcards(msg.meta!.flashcards!.set_id)
                  }
                />
              ) : null}

              {msg.meta?.note && !msg.streaming && (
                <NoteCard note={msg.meta.note} />
              )}

              {/* Exam-soon hand-off ("my exam is tomorrow"): a one-screen
                 cram setup under the answer, once its id is persisted. */}
              {msg.role === "assistant" &&
                !msg.streaming &&
                canPersist &&
                msg.id === lastOfferId &&
                msg.meta?.exam_prep_offer && (
                  <ExamPrepOfferCard
                    offer={msg.meta.exam_prep_offer}
                    messageId={msg.id}
                  />
                )}

              {/* Developer Mode diagnostics — debug users only, after the
                 turn has finished streaming. */}
              {isDebugUser &&
                msg.role === "assistant" &&
                !msg.streaming &&
                msg.meta?.debug && <DebugInfoPanel debug={msg.meta.debug} />}

              {/* A quiz/flashcard-only turn has nothing to act on; a team
                 turn that also answered keeps its actions and follow-ups. */}
              {msg.role === "assistant" &&
                !msg.streaming &&
                msg.content &&
                ((!msg.meta?.quiz && !msg.meta?.flashcards) ||
                  (team?.some((a) => a.kind === "answer") ?? false)) && (
                  <SuggestedActions
                    availableActions={msg.meta?.available_actions}
                    suggestedFollowups={msg.meta?.suggested_followups}
                    showSuggestions={msg.id === lastAssistantId}
                    busy={quizBusy}
                    topic={topic}
                    mediaAvailable={mediaAvailable}
                    quizBusy={quizBusy}
                    onAction={(message) => onAction(message, msg.content)}
                    onFollowup={onFollowup}
                    onGenerateQuiz={(opts) =>
                      onGenerateQuiz(topic, opts, msg.content)
                    }
                    onCreateFlashcards={() => onCreateFlashcards(msg.content)}
                    onCopy={() => copyMessage(msg.id, msg.content)}
                    onSaveNote={
                      // A generated note is already saved in Notes.
                      msg.meta?.note
                        ? undefined
                        : () => onSaveNote(msg.id, msg.content, topic)
                    }
                    onMakeNotes={
                      noteActions && notesEnabled && !msg.meta?.note
                        ? (instruction) => onAction(instruction, msg.content)
                        : undefined
                    }
                    canPersist={canPersist}
                    hideGenerators={isMetaAnswer(msg)}
                    feedback={
                      msg.id in ratings
                        ? ratings[msg.id]
                        : (msg.meta?.feedback?.rating ?? null)
                    }
                    onFeedback={
                      onFeedback
                        ? async (rating) => {
                            const ok = await onFeedback(
                              msg.id,
                              rating,
                              msg.meta?.tool_used,
                            );
                            if (ok) {
                              setRatings((prev) => ({
                                ...prev,
                                [msg.id]: rating,
                              }));
                            }
                            return ok;
                          }
                        : undefined
                    }
                    onRegenerate={
                      onRegenerate ? () => onRegenerate(msg.id) : undefined
                    }
                    bookmarkItem={{
                      item_type: "response",
                      item_ref: msg.id,
                      title: topic || msg.content.slice(0, 60),
                      content: msg.content,
                      metadata: {
                        tool_used: msg.meta?.tool_used,
                        sources: msg.meta?.sources ?? [],
                      },
                    }}
                  />
                )}
            </div>
          </motion.div>
        );
      })}
      <div ref={bottomRef} />
    </div>
  );
}
