// Renderer for a shared QUIZ_RESULT: score summary (never answers) with an
// "Attempt This Quiz" CTA into the quiz's own share. Used by SharePage.

import { useNavigate } from "react-router-dom";
import {
  CalendarDays,
  CheckCircle2,
  CircleDashed,
  Clock,
  HelpCircle,
  Play,
  Target,
  Trophy,
  XCircle,
} from "lucide-react";
import { GlassCard } from "@/components/common/GlassCard";
import { Button } from "@/components/ui/button";
import { ShareMetric } from "@/components/share/ShareMetric";
import { difficultyMeta, formatDuration, formatMarks } from "@/lib/quizFormat";
import { cn } from "@/lib/utils";
import type { SharedQuizResultContent } from "@/types";

/** One-line verdict for a score so the shared page reads like a report. */
function performanceSummary(score: number): string {
  if (score >= 90) return "Outstanding — near-perfect performance.";
  if (score >= 75) return "Great performance — most answers were correct.";
  if (score >= 50) return "Good effort — a solid base with room to grow.";
  if (score >= 25) return "Keep practicing — the fundamentals are forming.";
  return "A tough round — the next attempt can only go up.";
}

export function SharedResultView({
  content,
}: {
  content: SharedQuizResultContent;
}) {
  const navigate = useNavigate();
  const { quiz, result } = content;
  const diff = difficultyMeta(quiz.difficulty);
  const isExam =
    result.final_score !== undefined && result.final_score !== null;
  const attemptedOn = result.attempted_at
    ? new Date(result.attempted_at).toLocaleDateString()
    : "—";

  return (
    <GlassCard className="flex flex-col p-6">
      <div className="flex items-center gap-2">
        <span
          className={cn(
            "rounded-full px-2.5 py-0.5 text-[11px] font-semibold",
            diff.className,
          )}
        >
          {diff.label}
        </span>
        <span className="text-[11px] text-muted-foreground">
          Shared quiz result
        </span>
      </div>
      <h1 className="mt-3 font-display text-2xl font-bold">{quiz.title}</h1>
      {quiz.topic && (
        <p className="mt-1 text-sm text-muted-foreground">{quiz.topic}</p>
      )}

      {/* Score hero */}
      <div className="mt-5 rounded-2xl bg-brand-gradient p-6 text-center text-white shadow-glow">
        <Trophy className="mx-auto h-8 w-8" />
        <p className="mt-2 font-display text-5xl font-extrabold tabular-nums">
          {isExam
            ? formatMarks(result.final_score ?? 0, result.max_marks)
            : `${Math.round(result.score)}%`}
        </p>
        <p className="mt-1 text-sm opacity-90">
          {isExam
            ? `Final score · ${result.correct_count}/${result.total} correct · ${Math.round(result.score)}% accuracy`
            : `${result.correct_count}/${result.total} correct`}
        </p>
      </div>

      <p className="mt-4 text-center text-sm text-muted-foreground">
        {performanceSummary(result.score)}
      </p>

      {/* Summary tiles */}
      <div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-3">
        <ShareMetric
          icon={CheckCircle2}
          label="Correct"
          value={String(result.correct_count)}
        />
        <ShareMetric
          icon={XCircle}
          label="Incorrect"
          value={String(result.incorrect_count)}
        />
        <ShareMetric
          icon={CircleDashed}
          label="Unanswered"
          value={String(result.unanswered_count)}
        />
        <ShareMetric
          icon={Target}
          label="Accuracy"
          value={`${Math.round(result.score)}%`}
        />
        <ShareMetric
          icon={Clock}
          label="Time taken"
          value={formatDuration(result.time_taken_seconds ?? 0)}
        />
        <ShareMetric icon={CalendarDays} label="Attempted" value={attemptedOn} />
      </div>

      <div className="mt-3 flex items-center justify-center gap-1.5 text-xs text-muted-foreground">
        <HelpCircle className="h-3.5 w-3.5" />
        {quiz.question_count} questions
      </div>

      {/* Primary CTA: jump straight into attempting the same quiz. */}
      {content.quiz_share_id ? (
        <Button
          onClick={() => navigate(`/share/${content.quiz_share_id}`)}
          className="mt-6 w-full gap-2 bg-brand-gradient text-white"
        >
          <Play className="h-4 w-4" /> Attempt This Quiz
        </Button>
      ) : (
        <Button
          onClick={() => navigate("/")}
          className="mt-6 w-full gap-2 bg-brand-gradient text-white"
        >
          Try StudyAssistant free
        </Button>
      )}
      <p className="mt-3 text-center text-[11px] text-muted-foreground">
        Generated by StudyAssistant
      </p>
    </GlassCard>
  );
}
