// Renderer for a shared QUIZ: landing card → guest run → report. Used by the
// generic SharePage; submission goes through the generic share submit
// endpoint and is scored server-side.

import { useState } from "react";
import { Clock, Gauge, HelpCircle, ListChecks, Play } from "lucide-react";
import { GlassCard } from "@/components/common/GlassCard";
import { Button } from "@/components/ui/button";
import { QuizRunner } from "@/components/quiz/QuizRunner";
import { QuizAttemptReport } from "@/components/quiz/QuizAttemptReport";
import { ShareMetric } from "@/components/share/ShareMetric";
import { submitSharedQuiz } from "@/lib/api";
import { difficultyMeta, estimatedMinutes } from "@/lib/quizFormat";
import { cn } from "@/lib/utils";
import type { QuizContent, QuizSubmitResult } from "@/types";

type View = "landing" | "run" | "report";

export function SharedQuizView({
  shareId,
  quiz,
}: {
  shareId: string;
  quiz: QuizContent;
}) {
  const [view, setView] = useState<View>("landing");
  const [result, setResult] = useState<QuizSubmitResult | null>(null);

  const handleSubmit = async (
    answers: Record<string, string[]>,
    timeTakenSeconds: number,
  ): Promise<QuizSubmitResult> => {
    const { evaluation } = await submitSharedQuiz(
      shareId,
      answers,
      timeTakenSeconds,
    );
    return { attempt_id: "", evaluation };
  };

  const count = quiz.questions?.length ?? 0;
  const diff = difficultyMeta(quiz.difficulty ?? null);
  const minutes = estimatedMinutes(count, quiz.difficulty ?? null);

  if (view === "run") {
    return (
      <GlassCard className="flex flex-1 flex-col overflow-hidden p-0">
        <header className="flex items-center gap-2 border-b border-border/50 px-5 py-4">
          <ListChecks className="h-5 w-5 text-brand-1" />
          <h2 className="font-display text-base font-bold">{quiz.title}</h2>
        </header>
        <QuizRunner
          quiz={quiz}
          onSubmit={handleSubmit}
          onSubmitted={(res) => {
            setResult(res);
            setView("report");
          }}
        />
      </GlassCard>
    );
  }

  if (view === "report" && result) {
    return (
      <GlassCard className="flex flex-1 flex-col overflow-hidden p-0">
        <QuizAttemptReport
          quiz={quiz}
          evaluation={result.evaluation}
          attemptId={result.attempt_id}
          guest
          onClose={() => setView("landing")}
          onRetake={() => {
            setResult(null);
            setView("run");
          }}
        />
      </GlassCard>
    );
  }

  return (
    <GlassCard className="flex flex-col p-6">
      <span
        className={cn(
          "self-start rounded-full px-2.5 py-0.5 text-[11px] font-semibold",
          diff.className,
        )}
      >
        {diff.label}
      </span>
      <h1 className="mt-3 font-display text-2xl font-bold">{quiz.title}</h1>
      {quiz.topic && (
        <p className="mt-1 text-sm text-muted-foreground">{quiz.topic}</p>
      )}
      <p className="mt-4 text-sm text-muted-foreground">
        Test your knowledge with this {count}-question
        {quiz.topic ? ` ${quiz.topic}` : ""} quiz. Attempt it instantly — no
        sign-up needed.
      </p>

      <div className="mt-5 grid grid-cols-3 gap-2">
        <ShareMetric icon={HelpCircle} label="Questions" value={String(count)} />
        <ShareMetric icon={Gauge} label="Level" value={diff.label} />
        <ShareMetric icon={Clock} label="Est. time" value={`${minutes}m`} />
      </div>

      <Button
        onClick={() => setView("run")}
        className="mt-6 w-full gap-2 bg-brand-gradient text-white"
      >
        <Play className="h-4 w-4" /> Start Quiz
      </Button>
      <p className="mt-3 text-center text-[11px] text-muted-foreground">
        Generated by StudyAssistant
      </p>
    </GlassCard>
  );
}
