import { Seo } from "@/components/common/Seo";
import { PublicPage } from "@/components/landing/PublicPage";
import { PAGES, breadcrumbSchema } from "@/lib/seo";

export default function TermsPage() {
  return (
    <>
      <Seo
        title={PAGES.terms.title}
        description={PAGES.terms.description}
        path={PAGES.terms.path}
        jsonLd={breadcrumbSchema([
          { name: "Home", path: "/" },
          { name: "Terms of Service", path: "/terms" },
        ])}
      />
      <PublicPage
        title="Terms of Service"
        intro="The terms that govern your use of StudyAssistant."
      >
        <div className="prose prose-neutral max-w-none dark:prose-invert prose-headings:font-display">
          <h2>Acceptance of terms</h2>
          <p>
            By accessing or using StudyAssistant you agree to these Terms of
            Service. If you do not agree, please do not use the service.
          </p>

          <h2>Your account</h2>
          <p>
            You sign in with Google and are responsible for activity under your
            account. Keep your credentials secure and use the service only for
            lawful, personal study purposes.
          </p>

          <h2>Acceptable use</h2>
          <p>
            Don't use StudyAssistant to break the law, infringe others' rights,
            upload content you don't have the right to use, or attempt to disrupt
            or reverse-engineer the service. We may suspend accounts that abuse
            the platform.
          </p>

          <h2>Your content</h2>
          <p>
            You retain ownership of the notes, documents, and other content you
            upload. You grant us the limited rights needed to process and store
            that content so we can provide the service to you.
          </p>

          <h2>AI-generated content</h2>
          <p>
            Answers, quizzes, and flashcards are generated by AI and may contain
            errors. Verify important information — especially for exams,
            assignments, or decisions — against authoritative sources.
          </p>

          <h2>Service availability</h2>
          <p>
            StudyAssistant is provided "as is" without warranties. We may modify,
            suspend, or discontinue features at any time.
          </p>

          <h2>Contact</h2>
          <p>
            Questions about these terms? Reach us at{" "}
            <a href="mailto:support@studyassistant.app">
              support@studyassistant.app
            </a>
            .
          </p>
        </div>
      </PublicPage>
    </>
  );
}
